version: '3.3'
services:
  mcchttp:
    build: .
    ports:
      - 8080:8080
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
