version: '3.3'
services:
  green_shell:
    build: .
    ports:
      - 3839:3839
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined